### ISSUE TITLE
Running on MacOS platform Error ImportError: ('Unable to load EGL library', "dlopen(EGL, 0x000A): tried: 'EGL' (no such file)

### ISSUE THREAD

**Issue by yangxiaoleyxl** [caizhongang/SMPLer-X#65]
Traceback (most recent call last):
File "inference.py", line 188, in
main()
File "inference.py", line 57, in main
from utils.vis import render_mesh, save_obj
File "/Volumes/Work/Chinese_CV/CCM/Papers/SMPLer-X/main/../common/utils/vis.py", line 9, in
import pyrender
File "/Volumes/Work/Anaconda/anaconda3/envs/smplerx/lib/python3.8/site-packages/pyrender/init.py", line 3, in
from .light import Light, PointLight, DirectionalLight, SpotLight
File "/Volumes/Work/Anaconda/anaconda3/envs/smplerx/lib/python3.8/site-packages/pyrender/light.py", line 10, in
from OpenGL.GL import *
File "/Volumes/Work/Anaconda/anaconda3/envs/smplerx/lib/python3.8/site-packages/OpenGL/GL/init.py", line 3, in
from OpenGL import error as _error
File "/Volumes/Work/Anaconda/anaconda3/envs/smplerx/lib/python3.8/site-packages/OpenGL/error.py", line 12, in
from OpenGL import platform, _configflags
File "/Volumes/Work/Anaconda/anaconda3/envs/smplerx/lib/python3.8/site-packages/OpenGL/platform/init.py", line 35, in
_load()
File "/Volumes/Work/Anaconda/anaconda3/envs/smplerx/lib/python3.8/site-packages/OpenGL/platform/init.py", line 32, in _load
plugin.install(globals())
File "/Volumes/Work/Anaconda/anaconda3/envs/smplerx/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 92, in install
namespace[ name ] = getattr(self,name,None)
File "/Volumes/Work/Anaconda/anaconda3/envs/smplerx/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 14, in get
value = self.fget( obj )
File "/Volumes/Work/Anaconda/anaconda3/envs/smplerx/lib/python3.8/site-packages/OpenGL/platform/egl.py", line 93, in GetCurrentContext
return self.EGL.eglGetCurrentContext
File "/Volumes/Work/Anaconda/anaconda3/envs/smplerx/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 14, in get
value = self.fget( obj )
File "/Volumes/Work/Anaconda/anaconda3/envs/smplerx/lib/python3.8/site-packages/OpenGL/platform/egl.py", line 73, in EGL
raise ImportError("Unable to load EGL library", *err.args)
ImportError: ('Unable to load EGL library', "dlopen(EGL, 0x000A): tried: 'EGL' (no such file), '/System/Volumes/Preboot/Cryptexes/OSEGL' (no such file), '/Volumes/Work/Anaconda/anaconda3/envs/smplerx/lib/python3.8/lib-dynload/../../EGL' (no such file), '/Volumes/Work/Anaconda/anaconda3/envs/smplerx/bin/../lib/EGL' (no such file), '/usr/lib/EGL' (no such file, not in dyld cache), 'EGL' (no such file), '/usr/local/lib/EGL' (no such file), '/usr/lib/EGL' (no such file, not in dyld cache)", 'EGL', None)

ffmpeg -y -f image2 -r 24 -i /Volumes/Work/Chinese_CV/CCM/Papers/SMPLer-X/demo/results/test_video/img/%06d.jpg -vcodec mjpeg -qscale 0 -pix_fmt yuv420p /Volumes/Work/Chinese_CV/CCM/Papers/SMPLer-X/demo/results/test_video.mp4
ffmpeg version 7.0.1 Copyright (c) 2000-2024 the FFmpeg developers
built with Apple clang version 15.0.0 (clang-1500.1.0.2.5)
configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.0.1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
libavutil 59. 8.100 / 59. 8.100
libavcodec 61. 3.100 / 61. 3.100
libavformat 61. 1.100 / 61. 1.100
libavdevice 61. 1.100 / 61. 1.100
libavfilter 10. 1.100 / 10. 1.100
libswscale 8. 1.100 / 8. 1.100
libswresample 5. 1.100 / 5. 1.100
libpostproc 58. 1.100 / 58. 1.100
[image2 @ 0x13b91ff20] Could find no file with path '/Volumes/Work/Chinese_CV/CCM/Papers/SMPLer-X/demo/results/test_video/img/%06d.jpg' and index in the range 0-4
[in#0 @ 0x13b91e7c0] Error opening input: No such file or directory
Error opening input file /Volumes/Work/Chinese_CV/CCM/Papers/SMPLer-X/demo/results/test_video/img/%06d.jpg.
Error opening input files: No such file or directory
Hi, I meet the same error when running slurm_inference.sh of [https://github.com/caizhongang/SMPLer-X](SMLPer-X). 

Could any one give a solution ? Thanks

**Comment by Wei-Chen-hub** [comment]
Hi, thanks for your interest in our repo.

However, SMPLER-X is developed and tested only on Linux system. Other (Win and MacOS) are not guaranteed to be functional.

Based on your error message, the rendering tool which calls the GPU for rendering, 'EGL', is not avaliable in MacOS. You can either try to change to some rendering tool for MacOS or try to delete all related rendering code. But what i recommand is to switch to Linux device (Ubuntu or WSL2 in Windows).

Hope that helps.

**Comment by yangxiaoleyxl** [comment]
Thansk

> Hi, thanks for your interest in our repo.
> 
> However, SMPLER-X is developed and tested only on Linux system. Other (Win and MacOS) are not guaranteed to be functional.
> 
> Based on your error message, the rendering tool which calls the GPU for rendering, 'EGL', is not avaliable in MacOS. You can either try to change to some rendering tool for MacOS or try to delete all related rendering code. But what i recommand is to switch to Linux device (Ubuntu or WSL2 in Windows).
> 
> Hope that helps.

Thanks
