### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by xion-cyber** [caizhongang/SMPLer-X#69]
作者你好，
我在使用inference.py进行推理时遇到了很多关于版本的问题。
比如numpy版本过高会不支持bool类型，yapf版本过高会在FormatCode()中报错：TypeError: FormatCode() got an unexpected keyword argument ‘verify‘，pytorch我使用的1.12，但是在torchgeometry/core/conversions.py中会对mask进行一个反转操作，但是这个版本的pytorch不再支持这种bool类型的1-mask的操作，而是使用~mask来进行反转操作。
所以，作者您能提供完整的版本信息吗，不然一步一步找错太累了……
Thank you~

Traceback (most recent call last):
  File "/PaperCode/SMPLer-X/main/inference.py", line 135, in main
    out = demoer.model(inputs, targets, meta_info, 'test')
  File "/home/yeyiqi/.conda/envs/smplerx/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yeyiqi/.conda/envs/smplerx/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/yeyiqi/.conda/envs/smplerx/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/PaperCode/SMPLer-X/main/SMPLer_X.py", line 179, in forward
    root_pose = rot6d_to_axis_angle(root_pose)
  File "/PaperCode/SMPLer-X/common/utils/transforms.py", line 84, in rot6d_to_axis_angle
    axis_angle = tgm.rotation_matrix_to_angle_axis(rot_mat).reshape(-1, 3)  # axis-angle
  File "/home/yeyiqi/.conda/envs/smplerx/lib/python3.8/site-packages/torchgeometry/core/conversions.py", line 233, in rotation_matrix_to_angle_axis
    quaternion = rotation_matrix_to_quaternion(rotation_matrix)
  File "/home/yeyiqi/.conda/envs/smplerx/lib/python3.8/site-packages/torchgeometry/core/conversions.py", line 302, in rotation_matrix_to_quaternion
    mask_c1 = mask_d2 * (1 - mask_d0_d1)
  File "/home/yeyiqi/.conda/envs/smplerx/lib/python3.8/site-packages/torch/_tensor.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/home/yeyiqi/.conda/envs/smplerx/lib/python3.8/site-packages/torch/_tensor.py", line 639, in __rsub__
    return _C._VariableFunctions.rsub(self, other)
RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `logical_not()` operator instead.

**Comment by chuxiang93** [comment]
遇到完全一样的问题，前面的版本问题一个一个解决了，卡在了反转操作这。楼主有解决方案吗？

**Comment by xion-cyber** [comment]
> 遇到完全一样的问题，前面的版本问题一个一个解决了，卡在了反转操作这。楼主有解决方案吗？

版本问题可以通过搜索报错信息降低版本解决，然后应该是pytorch2.0之后不再支持bool类型的反转操作~了。然后需要你在torchgeometry/core/conversions.py这个文件中手动将mask矩阵的反转操作 ~ 改成 1-mask，之后估计就不会报这个错误了。

**Comment by wenbc21** [comment]
> > 遇到完全一样的问题，前面的版本问题一个一个解决了，卡在了反转操作这。楼主有解决方案吗？
> 
> 版本问题可以通过搜索报错信息降低版本解决，然后应该是pytorch2.0之后不再支持bool类型的反转操作~了。然后需要你在torchgeometry/core/conversions.py这个文件中手动将mask矩阵的反转操作 ~ 改成 1-mask，之后估计就不会报这个错误了。


1. 要指定yapf==0.40.1
2. 应该是把1-mask改成~mask

**Comment by AmitMY** [comment]
I am having a similar issue:
```py
/data/amoryo/conda/envs/smplerx/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "inference.py", line 188, in <module>
    main()
  File "inference.py", line 51, in main
    cfg.update_config(args.num_gpus, args.exp_name)
  File "/data/amoryo/other/SMPLer-X/main/../main/config.py", line 70, in update_config
    cfg_save.dump(osp.join(self.code_dir,'config_base.py'))
  File "/data/amoryo/conda/envs/smplerx/lib/python3.8/site-packages/mmcv/utils/config.py", line 596, in dump
    f.write(self.pretty_text)
  File "/data/amoryo/conda/envs/smplerx/lib/python3.8/site-packages/mmcv/utils/config.py", line 508, in pretty_text
    text, _ = FormatCode(text, style_config=yapf_style, verify=True)
TypeError: FormatCode() got an unexpected keyword argument 'verify'
```

Can the environment information / requirement / code be fixed directly in the codebase?

**Comment by skyhhh666** [comment]
@AmitMY May I ask if you have solved this problem? "TypeError: FormatCode() got an unexpected keyword argument 'verify',Thanks

**Comment by AmitMY** [comment]
@skyhhh666 I did not, and I haven't tried since.

**Comment by wenbc21** [comment]
> [@skyhhh666](https://github.com/skyhhh666) I did not, and I haven't tried since.



> [@AmitMY](https://github.com/AmitMY) May I ask if you have solved this problem? "TypeError: FormatCode() got an unexpected keyword argument 'verify',Thanks

pip install yapf==0.40.1
